<?php
/**
 * Created by PhpStorm.
 * User: qiaorui.chen
 * Date: 2018/3/2
 * Time: 上午11:43
 */
/**
 * @SWG\Swagger(
 *     basePath="",
 *     host="",
 *     schemes={"http","https"},
 *     produces={"application/json"},
 *     consumes={"application/json"},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Meowlomo ATM_MID API"
 *     ),
 *     @SWG\Definition(
 *         definition="ErrorModel",
 *         type="object",
 *         @SWG\Property(
 *             property="metadata",
 *             type="object",
 *             @SWG\Property(
 *                  property="object",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="nodeType",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="valueNode",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="floatingPointNumber",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="containerNode",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="missingNode",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="pojo",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="integralNumber",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="short",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="int",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="long",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="double",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="bigDecimal",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="bigInteger",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="textual",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="boolean",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="binary",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="float",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="number",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="array",
 *                  type="boolean"
 *             ),
 *             @SWG\Property(
 *                  property="null",
 *                  type="boolean"
 *             ),
 *         ),
 *         @SWG\Property(
 *             property="data",
 *             type="object"
 *         ),
 *         @SWG\Property(
 *             property="error",
 *             type="object"
 *         )
 *     )
 * )
 */

 //??application model

/**
 * @SWG\Definition(
 *   definition="application",
 *   type="object",
 *   @SWG\Property(
 *     property="id",
 *     type="integer",
 *   ),
 *   @SWG\Property(
 *     property="name",
 *     type="string",
 *   ),
 *   @SWG\Property(
 *     property="comment",
 *     type="string",
 *   ),
 *   @SWG\Property(
 *     property="createdAt",
 *     type="string",
 *     format="date-time"
 *   ),
 *   @SWG\Property(
 *     property="updatedAt",
 *     type="string",
 *     format="date-time"
 *   ),
 *   @SWG\Property(
 *     property="active",
 *     type="boolean",
 *   ),
 *   @SWG\Property(
 *     property="log",
 *     type="string",
 *   ),
 *   @SWG\Property(
 *     property="paramter",
 *     type="string",
 *   ),
 *   @SWG\Property(
 *     property="ownerId",
 *     type="integer",
 *     format="int32"
 *   ),
 *   @SWG\Property(
 *     property="sections",
 *     type="array",
 *     @SWG\Items(
 *       type="object",
 *       @SWG\Property(
 *         property="id",
 *         type="integer",
 *         format="int32",
 *       ),
 *       @SWG\Property(
 *         property="name",
 *         type="string",
 *       ),
 *       @SWG\Property(
 *         property="comment",
 *         type="string",
 *       ),
 *       @SWG\Property(
 *         property="createdAt",
 *         type="string",
 *         format="date-time",
 *       ),
 *       @SWG\Property(
 *         property="updatedAt",
 *         type="string",
 *         format="date-time",
 *       ),
 *       @SWG\Property(
 *         property="active",
 *         type="boolean",
 *       ),
 *       @SWG\Property(
 *         property="log",
 *         type="string",
 *       ),
 *       @SWG\Property(
 *         property="ownerId",
 *         type="integer",
 *       ),
 *       @SWG\Property(
 *         property="applicationId",
 *         type="integer",
 *       ),
 *       @SWG\Property(
 *         property="elements",
 *         type="array",
 *         @SWG\Items(
 *           type="object",
 *           @SWG\Property(
 *             property="id",
 *             type="integer"
 *           )
 *         )
 *       )
 *     )
 *   )
 * )
 */